from app.services.table_parser import TableParser

text = """| Focus                                   | Type       | ID     | Pre-Condition                                                      | Scenario                                                                                                  | Test Steps                                                                                                                                                                                    | Expected Result                                                                                                               | Result  | Notes / Issue |
| --------------------------------------- | ---------- | ------ | ------------------------------------------------------------------ | --------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------- | ------- | ------------- |
| Client Creation & Web Service Recording | Functional | TC-001 | User has access to application and permission to create new client | Verify newly created client is recorded in report after web service call                                  | 1. Login to application<br>2. Navigate to Client Management<br>3. Click Create New Client<br>4. Fill all mandatory fields<br>5. Save the client data<br>6. Verify client successfully created | New client is successfully created and visible in client list                                                                 | Pending |               |
| Client Creation & Web Service Recording | Functional | TC-002 | New client already created successfully                            | Verify web service can be called using newly created client                                               | 1. Open API/Web Service module<br>2. Select newly created client credentials<br>3. Trigger/call the web service endpoint<br>4. Observe response status and payload                            | Web service call returns success response (HTTP 200 / expected response)                                                      | Pending |               |
| Client Creation & Web Service Recording | Functional | TC-003 | Web service call completed successfully                            | Verify new client is recorded in report after web service execution                                       | 1. Navigate to Reporting page/module<br>2. Search using newly created client name or ID<br>3. Open generated report/log<br>4. Validate client data inside report                              | Newly created client is recorded correctly in report/log after web service call                                               | Pending |               |
| Client Creation & Web Service Recording | Functional | TC-004 | Existing report data available                                     | Verify recorded client data accuracy in report                                                            | 1. Compare client information from Client Management module with report data<br>2. Validate client name, ID, timestamp, and request details                                                   | Report contains correct and matching client information                                                                       | Pending |               |
| Client Creation & Web Service Recording | Negative   | TC-005 | Invalid client credentials prepared                                | Verify system behavior when invalid client calls web service                                              | 1. Create client with invalid/incomplete credentials OR modify credentials manually<br>2. Trigger web service call<br>3. Check report/log generation                                          | System rejects invalid request and logs proper error message without recording invalid transaction as successful              | Pending |               |
| Client Creation & Web Service Recording | Functional | TC-006 | System connected to database/reporting service                     | Verify report is generated in real-time after successful API call                                         | 1. Call web service using valid client<br>2. Refresh/open reporting page immediately<br>3. Search latest transaction                                                                          | Report entry appears within expected processing time                                                                          | Pending |               |
| Client Creation & Web Service Recording | Regression | TC-007 | Existing clients already recorded in report                        | Verify new client recording does not impact existing report data                                          | 1. Create and call web service using new client<br>2. Review old report entries<br>3. Validate existing data consistency                                                                      | Existing report data remains unchanged and accessible                                                                         | Pending |               |
| Date Range Validation                   | Functional | TC-008 | Reporting page is accessible                                       | Verify date range field accepts various date ranges and is not limited to last 1 month until current date | 1. Open reporting page<br>2. Input custom start date older than 1 month<br>3. Input custom end date<br>4. Click search/generate report                                                        | System allows users to input and search using various date ranges without restriction to only last 1 month until current date | Pending |               |
| Log Report Table Ordering               | Functional | TC-009 | Log report table contains data                                     | Verify user can sort/order data in log report table                                                       | 1. Open log report page<br>2. Click column header such as Date, Client Name, or Status<br>3. Observe table ordering<br>4. Click again to reverse sorting order                                | System successfully sorts log report table data in ascending and descending order based on selected column                    | Pending |               |"""

parser = TableParser()
res = parser.parse(text)
print("Dataframe shape:", res.dataframe.shape)
print("Dataframe:")
print(res.dataframe.head())
